export const pianoKeysInit = [
  {
    x: "1",
    y: "1",
    width: "24",
    height: "140",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "transparent",
    "data-key": "white",
    "data-note": "C",
  },
  {
    x: "25",
    y: "1",
    width: "24",
    height: "140",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "transparent",
    "data-key": "white",
    "data-note": "D",
  },
  {
    x: "49",
    y: "1",
    width: "24",
    height: "140",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "transparent",
    "data-key": "white",
    "data-note": "E",
  },
  {
    x: "73",
    y: "1",
    width: "24",
    height: "140",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "transparent",
    "data-key": "white",
    "data-note": "F",
  },
  {
    x: "97",
    y: "1",
    width: "24",
    height: "140",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "transparent",
    "data-key": "white",
    "data-note": "G",
  },
  {
    x: "121",
    y: "1",
    width: "24",
    height: "140",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "transparent",
    "data-key": "white",
    "data-note": "A",
  },
  {
    x: "145",
    y: "1",
    width: "24",
    height: "140",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "transparent",
    "data-key": "white",
    "data-note": "B",
  },
  {
    x: "18",
    y: "1",
    width: "14",
    height: "90",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "var(--text-color)",
    "data-key": "black",
    "data-note": "C#,Db",
  },
  {
    x: "42",
    y: "1",
    width: "14",
    height: "90",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "var(--text-color)",
    "data-key": "black",
    "data-note": "D#,Eb",
  },
  {
    x: "90",
    y: "1",
    width: "14",
    height: "90",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "var(--text-color)",
    "data-key": "black",
    "data-note": "F#,Gb",
  },
  {
    x: "114",
    y: "1",
    width: "14",
    height: "90",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "var(--text-color)",
    "data-key": "black",
    "data-note": "G#,Ab",
  },
  {
    x: "138",
    y: "1",
    width: "14",
    height: "90",
    rx: "2",
    ry: "2",
    stroke: "var(--text-color)",
    strokeWidth: "2",
    fill: "var(--text-color)",
    "data-key": "black",
    "data-note": "A#,Bb",
  },
];
